name: Parallel Jobs Example

on:
  pull_request:
    branches:
      - main
      - develop
      - feature/*
    types:
      - opened
    paths:
      - terraform/**

jobs:
  tflint:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 in Job 1
        run: echo "This is Job 1, Step 1"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Run tflint
        uses: ./.github/actions/tflint

  job2:
    runs-on: ubuntu-latest
    steps:
      - name: Step 1 in Job 2
        run: echo "This is Job 2, Step 1"
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}
